version: '3'

networks:
  appNet:

services:
 httpd:
  build: ./httpd
  ports:
    - 80:80
  links:
    - alfresco
    - adf
    - share
    - solr6 
  networks:
   appNet:
    aliases:
      - httpd

 adf:
  build: ./adf
  depends_on:
    - alfresco
  ports:
    - 3000:3000
  networks:
    appNet:
      aliases:
        - adf

 alfresco:
  build: ./alfresco
  depends_on:
    - db
  volumes:
    - ./alf_data:/usr/local/alfresco/alf_data
  networks:
   appNet:
    aliases:
      - alfresco
  environment:
   - LANG=en_US.utf8

 share:
  build: ./share
  depends_on:
    - alfresco
  networks:
   appNet:
    aliases:
      - share

 db:
  image: mariadb:latest
  volumes:
    - ./mariadb_data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=alfresco
    - MYSQL_DATABASE=alfresco
    - MYSQL_USER=alfresco
    - MYSQL_PASSWORD=alfresco
  networks:
   appNet:
    aliases:
      - db
  command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800]

# db:
#  image: postgres:10.1
#  environment:
#    - POSTGRES_PASSWORD=alfresco
#    - POSTGRES_USER=alfresco
#    - POSTGRES_DB=alfresco

 solr6:
  image: alfresco/alfresco-search-services:1.1.1
  depends_on:
    - alfresco
  environment:
    - SOLR_ALFRESCO_HOST=alfresco
    - SOLR_ALFRESCO_PORT=8080
    - SOLR_SOLR_HOST=solr6
    - SOLR_SOLR_PORT=8983
    - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
  volumes:
    - ./solr_data:/opt/alfresco-search-services/data
  networks:
   appNet:
    aliases:
      - solr6

 libreoffice:
  image: keensoft/libreoffice:latest
  networks:
   appNet:
    aliases:
      - libreoffice
